export {Homepage} from './Homepage/Homepage'
export {VideoListingPage} from './VideoListingPage/VideoListingPage'
export {SingleVideo} from './SingleVideoPage/SingleVideo'
export {SignIn} from './SignInPage/SignIn'
export {SignUp} from './SignUpPage/SignUp'
export {Profile} from './ProfilePage/Profile'
export {Like} from './LikePage/Like'
export {History} from './HistoryPage/History'