export const ACTION_TYPE={
    INITIAL_DATA:'INITIAL_DATA',
    INITIAL_CAT:'INITIAL_CAT',
    CATEGORIES: 'CATEGORIES',
    SORTBY:'SORTBY',
    SEARCH:'SEARCH',
    LIKE_HANDLER:'LIKE_HANDLER',
    HISTORY:'HISTORY',
    WATCHLATER_HANDLER:'WATCHLATER_HANDLER',
    PLAYLIST_HANDLER:'PLAYLIST_HANDLER',
    PLAYLIST_VIDEO_HANDLER:'PLAYLIST_VIDEO_HANDLER',
}